# Project information
site_name: 'Thremulation Station'
site_description: 'Local Elastic Static Security Testing'
site_author: 'Thremulation Station'
#site_url: 'https://github.com/mocyber/thremulation.io'


# Repository
repo_url: 'https://github.com/mocyber/thremulation.io'


#Copyright
copyright: 'Copyright &copy; 2020'


#Visual Configuration
theme:
  name: 'material'
  language: 'en'
  features:
    - navigation.tabs
  palette:
    primary: 'Black'
    accent: 'Blue Grey'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  icon:
    repo: fontawesome/brands/github
  #logo: 'img/station.png'
  #favicon: 'img/favicon.ico'


# # Customization
# extra:
#   #manifest: 'manifest.webmanifest'
#   social:
#     - type: 'github'
#       link: 'https://github.com/rocknsm'
#     - type: 'twitter'
#       link: 'https://twitter.com/rocknsm'


# Google Analytics
#google_analytics:
#  - '#'
#  - 'auto'


# Extensions
markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.superfences
#  - admonition
#  - codehilite:
#      guess_lang: false
#  - toc:
#      permalink: true


# Page Tree Layout
nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting-started/index.md
    - Topology: getting-started/topology.md
    - Node Details: getting-started/node-details.md
    - Installation: getting-started/installation.md
    - Deployment: getting-started/deployment.md
    - Functions Check: getting-started/functions-check.md
  - Toolset:
    - Overview: toolset/index.md
    - Caldera Usage: toolset/caldera-usage.md
  - Hunting Handbook:
    - What is Threat Hunting?: handbook/what-is-threathunting.md
    - Build Your Base: handbook/build-your-base.md
    - What's in the Data: handbook/whats-in-the-data.md
    - Tools of the Trade: handbook/tools.md
    - Developing a Methodology: handbook/developing-methodology.md
    - Understanding the Adversary: handbook/understanding-adversary.md
    - Platform Walkthrough: handbook/ts-walkthrough.md
    - Writing Resilient Detections: handbook/writing-detections.md
    - Lab 1 - Subtitle: handbook/lab1.md
    - Lab 2 - Subtitle: handbook/lab2.md
    - Lab 3 - Subtitle: handbook/lab3.md
  - Support: 
    - Support: support/index.md
    - References: support/references.md
  - Community: 
    - Contribution: contribution/index.md