# Project information
site_name: 'Thremulation Station'
site_description: 'Local Elastic Static Security Testing'
site_author: 'Thremulation Station'
site_url: 'https://thremulation.io'


# Repository
repo_url: 'https://github.com/thremulation-station/thremulation-station'


#Copyright
copyright: 'Copyright &copy; 2020'


#Visual Configuration
theme:
  name: 'material'
  language: 'en'
  features:
    - navigation.tabs
  palette:
    primary: 'Black'
    accent: 'Blue Grey'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  icon:
    repo: fontawesome/brands/github
  favicon: 'images/favicon.ico'
  logo: 'images/purple-lappy.png'
  


# # Customization
# extra:
#   #manifest: 'manifest.webmanifest'
#   social:
#     - type: 'github'
#       link: 'https://github.com/thremulation-station/thremulation-station'
#     - type: 'twitter'
#       link: 'https://twitter.com/thremulation'


# Google Analytics
#google_analytics:
#  - '#'
#  - 'auto'


# Extensions
markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.superfences
  - admonition
#  - codehilite:
#      guess_lang: false
#  - toc:
#      permalink: true


# Page Tree Layout
nav:
  - Home: 
    - index.md
    - community.md
    - contribution.md
  - About:
    - Overview: about/overview.md
    - Requirements: about/requirements.md
    - Machine Details: about/machine-details.md
    # - FAQs: about/faqs.md
  - Quickstart:
    - Installation: quickstart/installation.md
    - Deployment: quickstart/deployment.md
    - Initial Access: quickstart/initial-access.md
    - Functions Check: quickstart/functions-check.md
  - Tool Usage:
    - Overview: tool-usage/index.md
    - Caldera Usage: tool-usage/caldera-usage.md
    # - Atomic Usage: tool-usage/atomicredteam.md
  # - Hunting Handbook:
  #   - What is Threat Hunting?: handbook/what-is-threathunting.md
  #   - Build Your Base: handbook/build-your-base.md
  #   - What's in the Data: handbook/whats-in-the-data.md
  #   - Tools of the Trade: handbook/tools.md
  #   - Developing a Methodology: handbook/developing-methodology.md
  #   - Understanding the Adversary: handbook/understanding-adversary.md
  #   - Platform Walkthrough: handbook/ts-walkthrough.md
  #   - Writing Resilient Detections: handbook/writing-detections.md
  #   - Lab 1 - Subtitle: handbook/lab1.md
  #   - Lab 2 - Subtitle: handbook/lab2.md
  #   - Lab 3 - Subtitle: handbook/lab3.md
  - Support & Reference: 
    - Home: support/index.md
    - Station Control: support/stationctl.md
    - Troubleshooting: support/troubleshooting.md
    # - Glossary: support/glossary.md
    - External Reference: support/reference.md