name: Publish docs via GitHub Pages

on:
  push:
    branches: [ main, devel ]
  pull_request:
    branches: [ main, devel ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: mkdocs-gh-deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - name: Checkout main
      uses: actions/checkout@v1
        
    - name: Deploy docs
      uses: mhausenblas/mkdocs-deploy-gh-pages@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CUSTOM_DOMAIN: docs.thremulation.io
        CONFIG_FILE: folder/mkdocs.yml
        #EXTRA_PACKAGES: build-base